// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS9vJyTy_C_5n9NvhUNmVyUB6o8SJSPFk',
    appId: '1:854264043604:web:383e9e981c05e28bc6f5c1',
    messagingSenderId: '854264043604',
    projectId: 'to-be-c44a4',
    authDomain: 'to-be-c44a4.firebaseapp.com',
    storageBucket: 'to-be-c44a4.firebasestorage.app',
    measurementId: 'G-7X2DPYXW9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKDvH-5u0gDTZ7HGLxx5AnnrVd5blFaj4',
    appId: '1:854264043604:android:6c5f978278b52bc2c6f5c1',
    messagingSenderId: '854264043604',
    projectId: 'to-be-c44a4',
    storageBucket: 'to-be-c44a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDeaBfpUlTbonRvM3eBYYreq1vfAacs0Y',
    appId: '1:854264043604:ios:02a5a17dbc39cc33c6f5c1',
    messagingSenderId: '854264043604',
    projectId: 'to-be-c44a4',
    storageBucket: 'to-be-c44a4.firebasestorage.app',
    iosBundleId: 'com.example.to',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDeaBfpUlTbonRvM3eBYYreq1vfAacs0Y',
    appId: '1:854264043604:ios:02a5a17dbc39cc33c6f5c1',
    messagingSenderId: '854264043604',
    projectId: 'to-be-c44a4',
    storageBucket: 'to-be-c44a4.firebasestorage.app',
    iosBundleId: 'com.example.to',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS9vJyTy_C_5n9NvhUNmVyUB6o8SJSPFk',
    appId: '1:854264043604:web:c561e02964f20ba6c6f5c1',
    messagingSenderId: '854264043604',
    projectId: 'to-be-c44a4',
    authDomain: 'to-be-c44a4.firebaseapp.com',
    storageBucket: 'to-be-c44a4.firebasestorage.app',
    measurementId: 'G-7JSHJ8C07B',
  );
}
